# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish package to GitHub Packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build package
      run: mvn --batch-mode package --file pom.xml
    #  env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  Publish:
     needs: Build
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v1
       with:
         java-version: '11'
     - name: Create GitHub Release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
       with: 
         tag_name: v${{github.run_number}}
         release_name: Release V${{github.run_number}} 
         draft: false
         prerelease: false

     - name: Update version
       run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
     - name: Publish to GitHub Packages Apache Maven
       run: mvn -B deploy -DskipTests --file pom.xml
     #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
       env:
         GITHUB_TOKEN: ${{ github.token }}


     - name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: bengotch/samplepython:latest
