# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish package to GitHub Packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1. 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build package
      run: mvn --batch-mode package --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
      with: 
        tag_name: v${{github.run_number}}
        release_name: Release V${{github.run_number}} 
        draft: false
        prerelease: false

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy --file pom.xml
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        version: v${{github.run_number}}
